### ISSUE TITLE
Environment Variables  are incorrect in docker-compose.yaml 

### ISSUE THREAD

**Issue by murtaza-a** [smurtazakazmi/dock.s#1]
1. Variables incorrectly prefixed with **PHP_FPM_** (the need to be prefixed with **PHP_** only )
2. Network name is hard coded, need to use **${NETWORK_NAME}** variable
3. **APP_CONFIG_DIR** should be **APP_BASE_CONFIG_DIR**
4. **APP_LOG_DIR** should be **APP_BASE_LOG_DIR**

**Comment by smurtazakazmi** [comment]
Issue is fixed on commit a644c85.
